import React, { Component } from 'react';

export default class extends Component {
    render() {
        return (
            <div className="layout layout-triple">
                <div className="wrap">
                    <div className="panel">
                        <span>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas volutpat sollicitudin sapien eget eleifend. Curabitur ac euismod leo. Integer rhoncus lacinia aliquam. Vivamus eget est non erat dapibus ornare quis at augue. Curabitur vestibulum sapien non eros scelerisque, et eleifend justo bibendum. Pellentesque facilisis, nunc vel egestas mollis, nunc lacus semper leo, vitae euismod massa ante sed magna. Integer id tempor nulla, id cursus lacus. Fusce non leo sit amet lorem placerat facilisis in at velit. Phasellus ut ornare libero.

    Praesent tincidunt sapien porttitor ipsum imperdiet tristique. Sed dictum vitae augue at aliquet. Aenean congue luctus eros, ut laoreet enim venenatis lacinia. Suspendisse quis turpis id diam efficitur sollicitudin tristique ac ex. Sed imperdiet tellus augue, non porta lectus gravida eget. Phasellus at consequat nulla, posuere placerat lectus. Aliquam tristique sit amet libero at pretium. Vivamus aliquam lobortis scelerisque. Sed sit amet ullamcorper arcu, id sollicitudin leo. Integer vestibulum vitae libero in hendrerit. Nullam finibus odio a leo lacinia mattis. Duis dapibus nisl felis, at mollis erat feugiat vitae. Cras mi felis, consectetur et suscipit et, viverra et nisi. Pellentesque eu magna in sapien malesuada aliquet sit amet a quam. Duis sapien neque, tristique a elit in, iaculis egestas purus. Sed et scelerisque massa.

    Quisque dapibus arcu non nibh porttitor, sed molestie lorem luctus. Aenean eget malesuada tortor. Vivamus elementum, tellus at lobortis malesuada, nisi nulla viverra nibh, vitae tincidunt est neque vel elit. Duis eu euismod ipsum. Donec viverra justo lectus, et vulputate orci commodo non. Nulla pharetra nec nisi quis faucibus. Fusce pellentesque, augue a venenatis viverra, justo quam pharetra ligula, id porta quam odio nec libero. Mauris vitae orci sit amet odio gravida rhoncus. Suspendisse non placerat elit. Suspendisse neque metus, auctor bibendum nunc a, facilisis congue ex. Mauris ac purus dictum, commodo erat id, hendrerit arcu. Duis volutpat arcu at purus tincidunt, vitae malesuada ex pretium. Maecenas non dignissim lectus, vel gravida tortor. Suspendisse sed odio quis nunc hendrerit fringilla. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

    Morbi sollicitudin tempus lectus. Curabitur et diam lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla aliquet, mi rhoncus ultrices suscipit, tellus mauris dapibus lectus, volutpat vulputate metus ipsum nec ante. Integer maximus pulvinar justo, hendrerit venenatis tellus feugiat sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque volutpat, sapien id convallis placerat, neque felis laoreet odio, id convallis tellus augue eget nisi. Vivamus eu varius metus. Sed a vehicula est. Nulla semper purus nec nisi vehicula condimentum. Mauris est nunc, rhoncus quis consequat id, dignissim ut leo. Donec dapibus pharetra mi, eget porttitor quam maximus a. Praesent sem tortor, hendrerit cursus venenatis sit amet, egestas non libero. Cras cursus libero nec volutpat mollis. Aliquam porttitor, justo ut posuere ultrices, nisl augue suscipit nulla, eu blandit erat lacus ut turpis. Sed nec tellus tincidunt, laoreet eros at, interdum dolor.

    Nulla porta porttitor massa, in consectetur arcu hendrerit non. Phasellus quis ultrices lectus. Pellentesque mattis felis et finibus eleifend. Morbi tristique orci at augue tincidunt, at interdum dui congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum eget lacus sed urna varius pretium. In magna dolor, eleifend eget lectus non, volutpat venenatis ex.
                        </span>
                    </div>
                    <div className="panel">
                        <span>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas volutpat sollicitudin sapien eget eleifend. Curabitur ac euismod leo. Integer rhoncus lacinia aliquam. Vivamus eget est non erat dapibus ornare quis at augue. Curabitur vestibulum sapien non eros scelerisque, et eleifend justo bibendum. Pellentesque facilisis, nunc vel egestas mollis, nunc lacus semper leo, vitae euismod massa ante sed magna. Integer id tempor nulla, id cursus lacus. Fusce non leo sit amet lorem placerat facilisis in at velit. Phasellus ut ornare libero.

    Praesent tincidunt sapien porttitor ipsum imperdiet tristique. Sed dictum vitae augue at aliquet. Aenean congue luctus eros, ut laoreet enim venenatis lacinia. Suspendisse quis turpis id diam efficitur sollicitudin tristique ac ex. Sed imperdiet tellus augue, non porta lectus gravida eget. Phasellus at consequat nulla, posuere placerat lectus. Aliquam tristique sit amet libero at pretium. Vivamus aliquam lobortis scelerisque. Sed sit amet ullamcorper arcu, id sollicitudin leo. Integer vestibulum vitae libero in hendrerit. Nullam finibus odio a leo lacinia mattis. Duis dapibus nisl felis, at mollis erat feugiat vitae. Cras mi felis, consectetur et suscipit et, viverra et nisi. Pellentesque eu magna in sapien malesuada aliquet sit amet a quam. Duis sapien neque, tristique a elit in, iaculis egestas purus. Sed et scelerisque massa.

    Quisque dapibus arcu non nibh porttitor, sed molestie lorem luctus. Aenean eget malesuada tortor. Vivamus elementum, tellus at lobortis malesuada, nisi nulla viverra nibh, vitae tincidunt est neque vel elit. Duis eu euismod ipsum. Donec viverra justo lectus, et vulputate orci commodo non. Nulla pharetra nec nisi quis faucibus. Fusce pellentesque, augue a venenatis viverra, justo quam pharetra ligula, id porta quam odio nec libero. Mauris vitae orci sit amet odio gravida rhoncus. Suspendisse non placerat elit. Suspendisse neque metus, auctor bibendum nunc a, facilisis congue ex. Mauris ac purus dictum, commodo erat id, hendrerit arcu. Duis volutpat arcu at purus tincidunt, vitae malesuada ex pretium. Maecenas non dignissim lectus, vel gravida tortor. Suspendisse sed odio quis nunc hendrerit fringilla. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

    Morbi sollicitudin tempus lectus. Curabitur et diam lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla aliquet, mi rhoncus ultrices suscipit, tellus mauris dapibus lectus, volutpat vulputate metus ipsum nec ante. Integer maximus pulvinar justo, hendrerit venenatis tellus feugiat sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque volutpat, sapien id convallis placerat, neque felis laoreet odio, id convallis tellus augue eget nisi. Vivamus eu varius metus. Sed a vehicula est. Nulla semper purus nec nisi vehicula condimentum. Mauris est nunc, rhoncus quis consequat id, dignissim ut leo. Donec dapibus pharetra mi, eget porttitor quam maximus a. Praesent sem tortor, hendrerit cursus venenatis sit amet, egestas non libero. Cras cursus libero nec volutpat mollis. Aliquam porttitor, justo ut posuere ultrices, nisl augue suscipit nulla, eu blandit erat lacus ut turpis. Sed nec tellus tincidunt, laoreet eros at, interdum dolor.

    Nulla porta porttitor massa, in consectetur arcu hendrerit non. Phasellus quis ultrices lectus. Pellentesque mattis felis et finibus eleifend. Morbi tristique orci at augue tincidunt, at interdum dui congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum eget lacus sed urna varius pretium. In magna dolor, eleifend eget lectus non, volutpat venenatis ex.
                        </span>
                    </div>
                    <div className="panel">
                        <span>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas volutpat sollicitudin sapien eget eleifend. Curabitur ac euismod leo. Integer rhoncus lacinia aliquam. Vivamus eget est non erat dapibus ornare quis at augue. Curabitur vestibulum sapien non eros scelerisque, et eleifend justo bibendum. Pellentesque facilisis, nunc vel egestas mollis, nunc lacus semper leo, vitae euismod massa ante sed magna. Integer id tempor nulla, id cursus lacus. Fusce non leo sit amet lorem placerat facilisis in at velit. Phasellus ut ornare libero.

    Praesent tincidunt sapien porttitor ipsum imperdiet tristique. Sed dictum vitae augue at aliquet. Aenean congue luctus eros, ut laoreet enim venenatis lacinia. Suspendisse quis turpis id diam efficitur sollicitudin tristique ac ex. Sed imperdiet tellus augue, non porta lectus gravida eget. Phasellus at consequat nulla, posuere placerat lectus. Aliquam tristique sit amet libero at pretium. Vivamus aliquam lobortis scelerisque. Sed sit amet ullamcorper arcu, id sollicitudin leo. Integer vestibulum vitae libero in hendrerit. Nullam finibus odio a leo lacinia mattis. Duis dapibus nisl felis, at mollis erat feugiat vitae. Cras mi felis, consectetur et suscipit et, viverra et nisi. Pellentesque eu magna in sapien malesuada aliquet sit amet a quam. Duis sapien neque, tristique a elit in, iaculis egestas purus. Sed et scelerisque massa.

    Quisque dapibus arcu non nibh porttitor, sed molestie lorem luctus. Aenean eget malesuada tortor. Vivamus elementum, tellus at lobortis malesuada, nisi nulla viverra nibh, vitae tincidunt est neque vel elit. Duis eu euismod ipsum. Donec viverra justo lectus, et vulputate orci commodo non. Nulla pharetra nec nisi quis faucibus. Fusce pellentesque, augue a venenatis viverra, justo quam pharetra ligula, id porta quam odio nec libero. Mauris vitae orci sit amet odio gravida rhoncus. Suspendisse non placerat elit. Suspendisse neque metus, auctor bibendum nunc a, facilisis congue ex. Mauris ac purus dictum, commodo erat id, hendrerit arcu. Duis volutpat arcu at purus tincidunt, vitae malesuada ex pretium. Maecenas non dignissim lectus, vel gravida tortor. Suspendisse sed odio quis nunc hendrerit fringilla. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

    Morbi sollicitudin tempus lectus. Curabitur et diam lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla aliquet, mi rhoncus ultrices suscipit, tellus mauris dapibus lectus, volutpat vulputate metus ipsum nec ante. Integer maximus pulvinar justo, hendrerit venenatis tellus feugiat sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque volutpat, sapien id convallis placerat, neque felis laoreet odio, id convallis tellus augue eget nisi. Vivamus eu varius metus. Sed a vehicula est. Nulla semper purus nec nisi vehicula condimentum. Mauris est nunc, rhoncus quis consequat id, dignissim ut leo. Donec dapibus pharetra mi, eget porttitor quam maximus a. Praesent sem tortor, hendrerit cursus venenatis sit amet, egestas non libero. Cras cursus libero nec volutpat mollis. Aliquam porttitor, justo ut posuere ultrices, nisl augue suscipit nulla, eu blandit erat lacus ut turpis. Sed nec tellus tincidunt, laoreet eros at, interdum dolor.

    Nulla porta porttitor massa, in consectetur arcu hendrerit non. Phasellus quis ultrices lectus. Pellentesque mattis felis et finibus eleifend. Morbi tristique orci at augue tincidunt, at interdum dui congue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum eget lacus sed urna varius pretium. In magna dolor, eleifend eget lectus non, volutpat venenatis ex.
                        </span>
                    </div>
                </div>
            </div>
        );
    }
}
